name: Publish to npm

"on":
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: mbologna/.github/.github/workflows/npm-publish.yml@35de80cc0b53f3b0c99ad0c8658445026a1e44a7 # main
    with:
      node_version: lts/*
      package_manager: npm
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
